/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/EditMoviePage': RouteRecordInfo<'/EditMoviePage', '/EditMoviePage', Record<never, never>, Record<never, never>>,
    '/forbidden': RouteRecordInfo<'/forbidden', '/forbidden', Record<never, never>, Record<never, never>>,
    '/ForgotPasswordPage': RouteRecordInfo<'/ForgotPasswordPage', '/ForgotPasswordPage', Record<never, never>, Record<never, never>>,
    'LoginPage': RouteRecordInfo<'LoginPage', '/LoginPage', Record<never, never>, Record<never, never>>,
    '/ManageReviewsPage': RouteRecordInfo<'/ManageReviewsPage', '/ManageReviewsPage', Record<never, never>, Record<never, never>>,
    '/ManageRoles': RouteRecordInfo<'/ManageRoles', '/ManageRoles', Record<never, never>, Record<never, never>>,
    'Movie': RouteRecordInfo<'Movie', '/Movie', Record<never, never>, Record<never, never>>,
    '/NewPasswordPage': RouteRecordInfo<'/NewPasswordPage', '/NewPasswordPage', Record<never, never>, Record<never, never>>,
    'RegisterPage': RouteRecordInfo<'RegisterPage', '/RegisterPage', Record<never, never>, Record<never, never>>,
    '/ShowLists': RouteRecordInfo<'/ShowLists', '/ShowLists', Record<never, never>, Record<never, never>>,
    '/ShowMovies': RouteRecordInfo<'/ShowMovies', '/ShowMovies', Record<never, never>, Record<never, never>>,
  }
}
